debian/pgversions: Bump to 11+.
16:47:26 /<<PKGBUILDDIR>>/src/monitor/health_check_worker.c: In function ‘RegisterHealthCheckWorker’:
16:47:26 /<<PKGBUILDDIR>>/src/monitor/health_check_worker.c:417:23: error: ‘BackgroundWorker’ has no member named ‘bgw_type’
16:47:26   417 |         strlcpy(worker.bgw_type, "pgautofailover",
16:47:26       |                       ^
16:47:26 /<<PKGBUILDDIR>>/src/monitor/health_check_worker.c:418:38: error: ‘BackgroundWorker’ has no member named ‘bgw_type’
16:47:26   418 |                         sizeof(worker.bgw_type));
16:47:26       |                                      ^
16:47:26 make[2]: *** [<builtin>: health_check_worker.o] Error 1